### ISSUE TITLE
Fix Golem item Dupe bug, Brain jar experience bug and Thaumatorium crash game bug.

### ISSUE THREAD

**Issue by KELETU66666** [TheCodex6824/ThaumcraftFix#1]
I use bansouko fix those bug, link : https://github.com/KELETU66666/ThaumicRenaissanceKedition/tree/master/bansoukou/Thaumcraft-1.12.2-6.1.BETA26/thaumcraft/common
Hope you can fix those bug too :)

**Comment by TheCodex6824** [comment]
I forgot about some of those, thanks for the reminder!

**Comment by TheCodex6824** [comment]
These should all be fixed now. For the brain jar change, I only made it 10 ticks of delay to not slow down farms or whatever too much - if this needs to be tweaked it can be.
