### ISSUE TITLE
Strange Bug caused by Sanity Soap

### ISSUE THREAD

**Issue by KELETU66666** [TheCodex6824/ThaumcraftFix#16]
[crash-2024-07-08_00.46.36-server.txt](https://github.com/user-attachments/files/16144831/crash-2024-07-08_00.46.36-server.txt)

**Comment by TheCodex6824** [comment]
I don't think this is a Thaumcraft issue:

1. The line number in the stacktrace makes no sense (the entire class ends after about 110 lines)
2. The method in thaumcraft code that had the exception (`func_77615_a` / `onPlayerStoppedUsing`) does not call `random.nextInt` anywhere

I did also notice: `Thaumcraft-1.12.2-6.1.BETA26-patched.jar`, so it's possible there's a "patch" in there causing this. If not that, it's probably a coremod/mixin with a bug.

**Comment by KELETU66666** [comment]
> I don't think this is a Thaumcraft issue:
> 
> 1. The line number in the stacktrace makes no sense (the entire class ends after about 110 lines)
> 2. The method in thaumcraft code that had the exception (`func_77615_a` / `onPlayerStoppedUsing`) does not call `random.nextInt` anywhere
> 
> I did also notice: `Thaumcraft-1.12.2-6.1.BETA26-patched.jar`, so it's possible there's a "patch" in there causing this. If not that, it's probably a coremod/mixin with a bug.

thank you for your reply :)
