### ISSUE TITLE
Phials get consumed in creative

### ISSUE THREAD

**Issue by Vapaman** [TheCodex6824/ThaumcraftFix#20]
When putting phials into jars they get consumed and drop an empty phial in the inventory. Makes creative testing more tedious.

**Comment by TheCodex6824** [comment]
Yeah, I find this really annoying too.

**Comment by Vapaman** [comment]
Sanitizing Soap also suffers from the same problem

**Comment by TheCodex6824** [comment]
Both of these are fixed in 1.0.3.

**Comment by Vapaman** [comment]
Thank you so much!
