### ISSUE TITLE
ConcurrentModificationException on load with latest Actions build

### ISSUE THREAD

**Issue by xJon** [TheCodex6824/ThaumcraftFix#26]
https://mclo.gs/wdcJOmQ
Not sure if I did anything incorrectly?

**Comment by TheCodex6824** [comment]
I'm confused too. I just tried running the built jars from all 3 OS variations, and they all worked fine with a minimal set of mods. It's still possible I broke something with the action setup, but that crash seems really weird. And removing this mod fixes it?

**Comment by xJon** [comment]
Hm, it seems I cannot reproduce it. Never mind, then?

**Comment by xJon** [comment]
I *was* just able to reproduce it again: https://mclo.gs/bwR4kTa, however a simple relaunch "solved" it, and I can't accurately say it's caused by Thaumcraft Fix so I guess we can just keep an eye on it and keep this issue closed.

**Comment by TheCodex6824** [comment]
> I _was_ just able to reproduce it again: https://mclo.gs/bwR4kTa, however a simple relaunch "solved" it, and I can't accurately say it's caused by Thaumcraft Fix so I guess we can just keep an eye on it and keep this issue closed.

I suspect there is some kind of race condition between forge and one of your other mods messing with ingredients (such as trying to construct an instance of one while forge is in that loop), but I don't know if that's actually what's happening or which mod would be doing it.
