### ISSUE TITLE
JVM crash with Thaumic Wands

### ISSUE THREAD

**Issue by Wizzerinus** [TheCodex6824/ThaumcraftFix#30]
When the following list of mods is installed:
```
Baubles 1.12-1.5.2
Thaumcraft 1.12.2-6.1.BETA26
Thaumic Wands 1.2.7
Thaumcraft Fix 1.12.2-1.0.0
```
a JVM crash occurs. Crash log here: https://mclo.gs/4VCWzep

This doesn't occur with just one of Thaumic Wands and Thaumcraft Fix.

**Comment by TheCodex6824** [comment]
Please try 1.0.2 when you get a chance, this crash should be fixed there.

**Comment by TheCodex6824** [comment]
I'm going to close this since it seems like others are able to use Thaumic Wands with this mod now, but if it is still an issue for you we can reopen this.

**Comment by Wizzerinus** [comment]
Sorry for the slow response, laptop was in repair. Confirmed it working! Thank you.
