### ISSUE TITLE
[Feature Request] Dimension whitelist/blacklist for crystals

### ISSUE THREAD

**Issue by IcarussOne** [TheCodex6824/ThaumcraftFix#40]
Currently they spawn in any modded dimension and there is no way to prevent their generation except with AuraControl. I think it would be nice to also throw in this feature into this mod as well, but as a configurable whitelist/blacklist.

**Comment by TheCodex6824** [comment]
Yeah, AuraControl is also on my list of things to merge in. AuraControl should be a bit easier to integrate because it doesn't have as many external-facing components as Research Patcher does.
