### ISSUE TITLE
[Improvement/Bug] Lamplighter Infusion Enchantment does not work with the bore

### ISSUE THREAD

**Issue by Vapaman** [TheCodex6824/ThaumcraftFix#41]
The lamplighter infusion enchantment doesn't work with the arcane bore. This is inconsistent with other behaviour like destruction and refining. It also would be a nice addition since in this version placing an Arcane Lamp on the bore is not possible.

![2024-08-20_21 20 55](https://github.com/user-attachments/assets/0c1518bf-fa32-496b-a809-3eda4dddbdfb)
The bore isn't placing the intangible lightsources

**Comment by TheCodex6824** [comment]
This should work now, although I still need to make the bore menu show lamplighter like the other special properties
