### ISSUE TITLE
Useless categories show up again in the 1.0.4

### ISSUE THREAD

**Issue by Vapaman** [TheCodex6824/ThaumcraftFix#47]
![kuva](https://github.com/user-attachments/assets/60eb54b0-7c50-4bf8-a8fa-5850d4de5cbb)
Useless categories seem to show up again in the newest version of the mod even when they are meant to be disabled
![kuva](https://github.com/user-attachments/assets/93e276c7-0d7c-4b3f-8447-6cf274c74bc7)

**Comment by Vapaman** [comment]
Tested with Thaumic Augmentation 2.1.13

**Comment by TheCodex6824** [comment]
Yep, I messed up the category filter while trying to fix another bug. Hotfix incoming...

**Comment by TheCodex6824** [comment]
This should be fixed in 1.0.5.
