### ISSUE TITLE
1.0.5 TCFix conflict with TcResearchPatcher and not provide it's "CategoriesToRemove" function.

### ISSUE THREAD

**Issue by KELETU66666** [TheCodex6824/ThaumcraftFix#48]
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// There are four lights!

Time: 2024-09-10 11:09:09 CST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thaumcraft (thaumcraft)
Caused by: java.lang.VerifyError: Inconsistent stackmap frames at branch target 251
Exception Details:
  Location:
    thaumcraft/common/lib/research/ResearchManager.parseAllResearch()V @251: iinc
  Reason:
    Type top (current frame, locals[12]) is not assignable to 'com/google/gson/JsonObject' (stack map, locals[12])
  Current Frame:
    bci: @212
    flags: { }
    locals: { 'com/google/gson/JsonParser', 'java/util/Iterator', 'net/minecraft/util/ResourceLocation', 'java/lang/String', 'java/io/InputStream', 'java/io/InputStreamReader', 'com/google/gson/JsonObject', 'com/google/gson/JsonArray', integer, 'java/util/Iterator', 'com/google/gson/JsonElement', 'com/google/gson/JsonObject' }
    stack: { integer }
  Stackmap Frame:
    bci: @251
    flags: { }
    locals: { 'com/google/gson/JsonParser', 'java/util/Iterator', 'net/minecraft/util/ResourceLocation', 'java/lang/String', 'java/io/InputStream', 'java/io/InputStreamReader', 'com/google/gson/JsonObject', 'com/google/gson/JsonArray', integer, 'java/util/Iterator', 'com/google/gson/JsonElement', 'com/google/gson/JsonElement', 'com/google/gson/JsonObject' }
    stack: { }
  Bytecode:
    0x0000000: b801 ceb8 01d3 bb01 d559 b701 d64b b201
    0x0000010: dcb6 01df b901 6501 004c 2bb9 0150 0100
    0x0000020: 9901 8b2b b901 5401 00c0 01e1 4dbb 01e3
    0x0000030: 59b7 01e4 1301 e6b6 01ea 2cb6 01ed b601
    0x0000040: ea13 01ef b601 ea2c b601 f2b6 01ea b601
    0x0000050: f54e 2d13 01f7 b601 fa9a 0018 bb01 e359
    0x0000060: b701 e42d b601 ea13 01f7 b601 eab6 01f5
    0x0000070: 4e12 022d b602 002c b802 043a 0419 04c6
    0x0000080: 010a bb02 0659 1904 b702 093a 052a 1905
    0x0000090: b602 0db6 0213 3a06 1906 1302 15b6 021b
    0x00000a0: b602 1f3a 0703 3608 1907 b602 223a 0919
    0x00000b0: 09b9 0150 0100 9900 8219 09b9 0154 0100
    0x00000c0: c002 0f3a 0a84 0801 190a b602 133a 0b19
    0x00000d0: 0bb8 0228 9900 2784 0801 190b b802 2b99
    0x00000e0: 0019 8408 0119 0bb8 022f 3a0c 190c b802
    0x00000f0: 3319 0b19 0cb8 0237 8408 ff84 08ff a700
    0x0000100: 373a 0b19 0bb6 023a b202 40bb 01e3 59b7
    0x0000110: 01e4 1302 42b6 01ea 1508 b602 4513 0247
    0x0000120: b601 ea2c b602 48b6 01ea b601 f5b9 024e
    0x0000130: 0200 8408 ffa7 ff7a b202 40bb 01e3 59b7
    0x0000140: 01e4 1302 50b6 01ea 1508 b602 4513 0252
    0x0000150: b601 ea2c b602 48b6 01ea b601 f5b9 0255
    0x0000160: 0200 a700 463a 05b2 0240 bb01 e359 b701
    0x0000170: e413 0257 b601 ea2c b602 48b6 01ea b601
    0x0000180: f5b9 024e 0200 a700 22b2 0240 bb01 e359
    0x0000190: b701 e413 0259 b601 ea2c b602 48b6 01ea
    0x00001a0: b601 f5b9 024e 0200 a7fe 72b8 025c b802
    0x00001b0: 5fb1                                   
  Exception Handler Table:
    bci [200, 251] => handler: 257
    bci [130, 354] => handler: 357
  Stackmap Table:
    append_frame(@26,Object[#469],Object[#333])
    append_frame(@113,Object[#481],Object[#116])
    full_frame(@175,{Object[#469],Object[#333],Object[#481],Object[#116],Object[#548],Object[#518],Object[#535],Object[#545],Integer,Object[#333]},{})
    append_frame(@248,Object[#527])
    append_frame(@251,Object[#527],Object[#535])
    full_frame(@257,{Object[#469],Object[#333],Object[#481],Object[#116],Object[#548],Object[#518],Object[#535],Object[#545],Integer,Object[#333],Object[#527]},{Object[#459]})
    append_frame(@309,Object[#4])
    chop_frame(@312,2)
    full_frame(@357,{Object[#469],Object[#333],Object[#481],Object[#116],Object[#548]},{Object[#459]})
    same_frame(@393)
    same_frame(@424)
    chop_frame(@427,3)

    at thaumcraft.common.config.ConfigResearch.postInit(ConfigResearch.java:135)
    at thaumcraft.proxies.CommonProxy.postInit(CommonProxy.java:87)
    at thaumcraft.proxies.ClientProxy.postInit(ClientProxy.java:54)
    at thaumcraft.Thaumcraft.postInit(Thaumcraft.java:54)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3601)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:110)
    at oolloo.jlw.Wrapper.main(Wrapper.java:103)

No Mixin Metadata is found in the Stacktrace.

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_332, Temurin
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
  Memory: 219891504 bytes (209 MB) / 1322778624 bytes (1261 MB) up to 7549222912 bytes (7199 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn1136m -Xmx7577m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 LoliASM 5.20 Powered by Forge 14.23.5.2860 65 mods loaded, 65 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                      | Version                 | Source                                      | Signature                                |
       |:----- |:----------------------- |:----------------------- |:------------------------------------------- |:---------------------------------------- |
       | LCHIJ | minecraft               | 1.12.2                  | minecraft.jar                               | None                                     |
       | LCHIJ | mcp                     | 9.42                    | minecraft.jar                               | None                                     |
       | LCHIJ | FML                     | 8.0.99.99               | forge-1.12.2-14.23.5.2860.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJ | forge                   | 14.23.5.2860            | forge-1.12.2-14.23.5.2860.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJ | smoothfontcore          | mc1.12.2-2.1.4          | minecraft.jar                               | None                                     |
       | LCHIJ | xaerominimap_core       | 1.12.2-1.0              | minecraft.jar                               | None                                     |
       | LCHIJ | xaeroworldmap_core      | 1.12.2-1.0              | minecraft.jar                               | None                                     |
       | LCHIJ | mixinbooter             | 9.3                     | minecraft.jar                               | None                                     |
       | LCHIJ | smoothfont              | mc1.12.2-2.1.4          | SmoothFont-mc1.12.2-2.1.4.jar               | None                                     |
       | LCHIJ | configanytime           | 3.0                     | !configanytime-3.0.jar                      | None                                     |
       | LCHIJ | baubles                 | 1.5.2                   | Baubles-1.12-1.5.2.jar                      | None                                     |
       | LCHIE | thaumcraft              | 6.1.BETA26              | Thaumcraft-1.12.2-6.1.BETA26.jar            | None                                     |
       | LCHI  | thaumicaugmentation     | 1.12.2-2.1.13           | ThaumicAugmentation-1.12.2-2.1.13.jar       | None                                     |
       | LCHI  | advanced_smelter        | 1.1.0                   | Advanced Essentia Smelter-1.1.0.jar         | None                                     |
       | LCHI  | jei                     | 4.16.1.301              | jei_1.12.2-4.16.1.301.jar                   | None                                     |
       | LCHI  | appleskin               | 1.0.14                  | AppleSkin-mc1.12-1.0.14.jar                 | None                                     |
       | LCHI  | betterquesting          | 4.2.3                   | BetterQuestingUnofficial-4.2.3.jar          | None                                     |
       | LCHI  | botania                 | r1.10-364               | Botania r1.10-364.4.jar                     | None                                     |
       | LCHI  | loliasm                 | 5.20                    | censoredasm5.20.jar                         | None                                     |
       | LCHI  | chameleon               | 1.12-4.1.3              | Chameleon-1.12-4.1.3.jar                    | None                                     |
       | LCHI  | ctm                     | MC1.12.2-1.0.2.31       | CTM-MC1.12.2-1.0.2.31.jar                   | None                                     |
       | LCHI  | chisel                  | MC1.12.2-1.0.2.45       | Chisel-MC1.12.2-1.0.2.45.jar                | None                                     |
       | LCHI  | containerfix            | 1.0                     | ContainerFix MC1.12.2 v1.0.jar              | None                                     |
       | LCHI  | custommainmenu          | 2.0.9.1                 | CustomMainMenu-MC1.12.2-2.0.9.1.jar         | None                                     |
       | LCHI  | findme                  | 1.1.0                   | findme-1.12.2-1.1.0-8.jar                   | None                                     |
       | LCHI  | forgotten_relics        | 0.6.2                   | ForgottenRelicsKedition-0.6.3.jar           | None                                     |
       | LCHI  | ftblib                  | 5.4.7.2                 | FTBLib-5.4.7.2.jar                          | None                                     |
       | LCHI  | ftbutilities            | 5.4.1.131               | FTBUtilities-5.4.1.131.jar                  | None                                     |
       | LCHI  | gravestone              | 1.10.3                  | gravestone-1.10.3.jar                       | None                                     |
       | LCHI  | waila                   | 1.8.26                  | Hwyla-1.8.26-B41_1.12.2.jar                 | None                                     |
       | LCHI  | ias                     | D7.29 :P                | InGameAccountSwitcher-Forge-1.12-8.0.1.jar  | None                                     |
       | LCHI  | inventorytweaks         | 1.64+dev.151.822d839    | InventoryTweaks-1.64+dev.151.jar            | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHI  | isorropia               | 0.1.13                  | isorropia-1.12.2-kedition-0.0.1.jar         | None                                     |
       | LCHI  | itlt                    | 1.0.4                   | itlt-1.12.x-1.0.4.jar                       | None                                     |
       | LCHI  | lostmagic               | 1.0                     | lostmagic-1.0.3.jar                         | None                                     |
       | LCHI  | tbone                   | v1.6.8+mc1.12.2         | TBone-v1.6.8+mc1.12.2.jar                   | None                                     |
       | LCHI  | metalchests             | v6.1.0+mc1.12.2         | MetalChests-v6.1.0+mc1.12.2.jar             | None                                     |
       | LCHI  | morpheus                | 1.12.2-3.5.106          | Morpheus-1.12.2-3.5.106.jar                 | None                                     |
       | LCHI  | mousetweaks             | 3.1.4                   | mousetweaks-1.12.2-3.1.4.jar                | None                                     |
       | LCHI  | nanhealthfixer          | 1.12.2-0.0.1            | nanhealthfixer-1.12.2-0.0.1.jar             | None                                     |
       | LCHI  | crimsonrevelations      | 1.1.0                   | New-Crimson-Revelations-1.1.0.jar           | None                                     |
       | LCHI  | thaumicwonders          | 1.9.0                   | New-Wonderology-1.12.2-1.9.0.jar            | None                                     |
       | LCHI  | planarartifice          | 1.0.0                   | PlanarArtificeKedition-1.0.0.jar            | None                                     |
       | LCHI  | forbiddenmagicre        | 0.7.5                   | ReForbidden Magic-1.12.2-v0.7.7.jar         | None                                     |
       | LCHI  | renaissance_core        | 1.0.0                   | renaissance_core-0.0.3.jar                  | None                                     |
       | LCHI  | resourceloader          | 1.5.3                   | ResourceLoader-MC1.12.1-1.5.3.jar           | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHI  | storagedrawers          | 5.5.1                   | StorageDrawers-1.12.2-5.5.1.jar             | None                                     |
       | LCHI  | storagedrawersunlimited | 1.12.2-1.3.0            | StorageDrawersUnlimited-1.12.2-1.3.0.jar    | None                                     |
       | LCHI  | thaumcraftfix           | 1.12.2-1.0.5            | ThaumcraftFix-1.12.2-1.0.5.jar              | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
       | LCHI  | thaumcraftjarchecker    | 1.0                     | ThaumcraftJarChecker-1.12.2-1.0a.jar        | None                                     |
       | LCHI  | tcresearchpatcher       | 1.12.2-1.1.3            | ThaumcraftResearchPatcher-1.12.2-1.1.3.jar  | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
       | LCHI  | thaumicbases            | 3.5.300.0               | thaumicbases-3.5.302.0.jar                  | None                                     |
       | LCHI  | thaumicbrewing          | 1.0.2                   | thaumicbrewing-1.0.2.jar                    | None                                     |
       | LCHI  | thaumicgadgets          | 0.4.0-kedition          | ThaumicGadgets-0.4.0-kedition.jar           | None                                     |
       | LCHI  | tcinventoryscan         | 2.0.10                  | ThaumicInventoryScanning_1.12.2-2.0.10.jar  | None                                     |
       | LCHI  | thaumicjei              | 1.6.0                   | ThaumicJEI-1.12.2-1.7.0.jar                 | None                                     |
       | LCHI  | thaumicperiphery        | 0.3.1                   | thaumicperiphery-0.3.1.jar                  | None                                     |
       | LCHI  | thaumictinkerer         | 1.12.2-5.5.2-Unofficial | thaumictinkerer-1.12.2-5.5.2-Unofficial.jar | None                                     |
       | LCHI  | universaltweaks         | 1.12.0                  | UniversalTweaks-1.12.2-1.12.0.jar           | None                                     |
       | LCHI  | voidgoggles             | 0.1.0                   | voidgoggles-0.1.0.jar                       | None                                     |
       | LCHI  | wanionlib               | 1.12.2-2.91             | WanionLib-1.12.2-2.91.jar                   | None                                     |
       | LCHI  | warptheory              | 0.0.3.6                 | WarpTheory1.12.2-0.0.3.8.jar                | None                                     |
       | LCHI  | xaerominimap            | 24.3.0                  | Xaeros_Minimap_24.3.0_Forge_1.12.jar        | None                                     |
       | LCHI  | xaeroworldmap           | 1.39.0                  | XaerosWorldMap_1.39.0_Forge_1.12.jar        | None                                     |
       | LCHI  | unidict                 | 1.12.2-3.0.10           | UniDict-1.12.2-3.0.10.jar                   | None                                     |
  Loaded coremods (and transformers): Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      Thaumcraft Research Patcher Core Plugin (ThaumcraftResearchPatcher-1.12.2-1.1.3.jar)
                                        thecodex6824.tcresearchpatcher.Transformer
                                      UniversalTweaksCore (UniversalTweaks-1.12.2-1.12.0.jar)
                                        
                                      XaeroMinimapPlugin (Xaeros_Minimap_24.3.0_Forge_1.12.jar)
                                        xaero.common.core.transformer.ChunkTransformer
                                        xaero.common.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.common.core.transformer.EntityPlayerTransformer
                                        xaero.common.core.transformer.AbstractClientPlayerTransformer
                                        xaero.common.core.transformer.WorldClientTransformer
                                        xaero.common.core.transformer.EntityPlayerMPTransformer
                                        xaero.common.core.transformer.EntityPlayerSPTransformer
                                        xaero.common.core.transformer.PlayerListTransformer
                                        xaero.common.core.transformer.SaveFormatTransformer
                                        xaero.common.core.transformer.GuiIngameForgeTransformer
                                        xaero.common.core.transformer.MinecraftServerTransformer
                                        xaero.common.core.transformer.GuiBossOverlayTransformer
                                        xaero.common.core.transformer.ModelRendererTransformer
                                      Thaumcraft Fix Core Plugin (ThaumcraftFix-1.12.2-1.0.5.jar)
                                        thecodex6824.thaumcraftfix.core.TransformerExecutor
                                      CorePlugin (SmoothFont-mc1.12.2-2.1.4.jar)
                                        bre.smoothfont.asm.Transformer
                                      XaeroWorldMapPlugin (XaerosWorldMap_1.39.0_Forge_1.12.jar)
                                        xaero.map.core.transformer.ChunkTransformer
                                        xaero.map.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.map.core.transformer.EntityPlayerTransformer
                                        xaero.map.core.transformer.AbstractClientPlayerTransformer
                                        xaero.map.core.transformer.WorldClientTransformer
                                        xaero.map.core.transformer.EntityPlayerMPTransformer
                                        xaero.map.core.transformer.PlayerListTransformer
                                        xaero.map.core.transformer.SaveFormatTransformer
                                        xaero.map.core.transformer.BiomeColorHelperTransformer
                                        xaero.map.core.transformer.MinecraftServerTransformer
                                        xaero.map.core.transformer.MinecraftTransformer
                                      Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.13.jar)
                                        thecodex6824.thaumicaugmentation.core.TATransformer
                                      LoliASM (censoredasm5.20.jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      UniDictCoreMod (UniDict-1.12.2-3.0.10.jar)
                                        wanion.unidict.core.UniDictCoreModTransformer
                                      MixinBooter (!mixinbooter-9.3.jar)
                                        
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      ConfigAnytimePlugin (!configanytime-3.0.jar)
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 511.69' Renderer: 'NVIDIA GeForce RTX 2060/PCIe/SSE2'
  Suspected Mods: Thaumcraft (thaumcraft), Forge Mod Loader (FML), Minecraft Forge (forge)
  Launched Version: 神秘复兴
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 511.69, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Inlay Fix 1.0.zip, Sonomagy TC6 v1.6.zip, Thaum_pack.zip (incompatible), jappabp-1.2-mc1.12.zip, ThaumMenu1.2.zip
  Current Language: 简体中文 (中国)
  Profiler Position: N/A (disabled)
  CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

**Comment by xJon** [comment]
I thought Thaumcraft Fix includes Research Patcher in it?

**Comment by TheCodex6824** [comment]
> I thought Thaumcraft Fix includes Research Patcher in it?

It does, but I intended to allow the standalone Research Patcher to still work to not break modpacks. That did not seem to go well.

The missing "CategoriesToRemove" config is intentional because I fixed the category auto-detection to support more addons. However, it seems I forgot to actually remove the categories.

**Comment by TheCodex6824** [comment]
@KELETU66666, can you give the latest actions build a try and see if this fixes your issue? I want to make sure the fix is consistent before releasing it.

Also, we can talk about CategoriesToRemove if you still need it. The reason I didn't add it back was because the only usecase I could think of for removing categories is after moving all of the research out of them, but if there are other uses this doesn't help then I can add it back.

**Comment by KELETU66666** [comment]
> @KELETU66666, can you give the latest actions build a try and see if this fixes your issue? I want to make sure the fix is consistent before releasing it.
> 
> Also, we can talk about CategoriesToRemove if you still need it. The reason I didn't add it back was because the only usecase I could think of for removing categories is after moving all of the research out of them, but if there are other uses this doesn't help then I can add it back.

got it :)

**Comment by KELETU66666** [comment]
btw, can you send a release about this update :) ? my pack need this update :)
