### ISSUE TITLE
Scatter Modifier Question

### ISSUE THREAD

**Issue by FantasyShark** [TheCodex6824/ThaumcraftFix#52]
Is it intended that you can't put a scatter modifier after any trajectory pattern? I tried bolt-scatter-bolt and projectile-scatter-projectile and just couldn't start the creating.

**Comment by TheCodex6824** [comment]
Nope, that was a bug in the foci validator. I noticed I also broke something else with the focal manipulator so hotfix coming soon

**Comment by TheCodex6824** [comment]
This is fixed in 1.0.7. By the way, are you the person that left a comment on CurseForge asking about something similar to this?

**Comment by FantasyShark** [comment]
> This is fixed in 1.0.7. By the way, are you the person that left a comment on CurseForge asking about something similar to this?

Great job. And no, that's not me.
