### ISSUE TITLE
Small incompatibility with ThaumTweaks 

### ISSUE THREAD

**Issue by xJon** [TheCodex6824/ThaumcraftFix#53]
- With ThaumTweaks:
![image](https://github.com/user-attachments/assets/b12ef4e5-0f5a-4d9b-bde7-6e822e1d8101)

- With ThaumTweaks + Thaumcraft Fix:
![image](https://github.com/user-attachments/assets/d9a2b003-1533-4d0c-95ed-82c7ed4157a7)

**Comment by TheCodex6824** [comment]
This is related to the primordial pearl change to use metadata instead of damage values. I'll be adding a config option to toggle that fix, since it's not possible for me to keep the fix and allow things like this that depend on the normal item to work.
