### ISSUE TITLE
[Bug] TCFix breaks Thaumic Wonders primordial accelerator's output

### ISSUE THREAD

**Issue by jchung01** [TheCodex6824/ThaumcraftFix#54]
Thaumic Wonders has a multiblock-like structure called the primordial accelerator to convert primordial pearls into primordial grains. With ThaumcraftFix installed, the accelerator will consume the pearl, but not output/drop any grains. Without Thaumcraft Fix, the grains drop as expected.

This is probably because the accelerator checks the primordial pearl's max damage with `Item#getMaxDamage()` [here](https://github.com/daedalus4096/ThaumicWonders/blob/master/src/main/java/com/verdantartifice/thaumicwonders/common/tiles/devices/TilePrimordialAccelerator.java#L94), but TCFix sets the max damage of the pearl to 0 [here](https://github.com/TheCodex6824/ThaumcraftFix/blob/main/src/main/java/thecodex6824/thaumcraftfix/mixin/item/ItemPrimordialPearlMixin.java#L53). This is probably a similar situation to #53.

The structure looks like this (Primordial Accelerator -> Tunnels -> Terminus), and upon inserting a pearl in the accelerator and giving it a redstone signal, grains should drop at the terminus.
![2024-10-24_14 06 56](https://github.com/user-attachments/assets/898055ed-fc46-4f41-8488-80bd7a48df37)

**Comment by TheCodex6824** [comment]
You're correct, this is the same thing as #53. I'll be adding a config option to not apply this fix.
